# Generated by Django 3.2.9 on 2022-10-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=20)),
                ('car_picture', models.ImageField(upload_to='')),
                ('works', models.TextField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
    ]
