# Generated by Django 3.2.9 on 2022-10-17 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site_app', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_site_app.gallery')),
            ],
        ),
    ]
