# Generated by Django 3.2.9 on 2022-10-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_site_app', '0003_carimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImages',
        ),
    ]
